import type { CSSProperties } from "react";

/**
 * 产品视觉的唯一配置入口。
 * 更换品牌色、字号或圆角时，只修改这里；Ant Design 和项目 CSS 会同步更新。
 */
export const designTokens = {
  colors: {
    brand: "#2f766d",
    brandHover: "#255f57",
    brandActive: "#1f504a",
    brandSoft: "#e7f1ef",
    brandSoftStrong: "#d8e9e5",
    focusRing: "rgba(47, 118, 109, 0.14)",
    appBackground: "#f5f7f7",
    surface: "#ffffff",
    surfaceSubtle: "#f7f9f8",
    surfaceMuted: "#eef2f1",
    surfaceHeader: "#fbfcfc",
    sidebar: "#fafbfb",
    text: "#1e2926",
    textSecondary: "#5f6c68",
    textMuted: "#899490",
    border: "#e3e8e6",
    borderStrong: "#d7dedb",
    action: "#20231f",
    actionHover: "#10120f",
    actionActive: "#050604",
    danger: "#a7474f",
    rowFeature: "#fafcfb",
    rowHover: "#f4f8f7",
  },
  status: {
    neutral: { background: "#eae8e2", text: "#5e605b" },
    design: { background: "#e5ece5", text: "#356042" },
    info: { background: "#e3efec", text: "#2f6e63" },
    warning: { background: "#f3ebdd", text: "#7a5b27" },
    success: { background: "#e5eee7", text: "#356145" },
    completed: { background: "#dcebe2", text: "#24563a" },
    error: { background: "#f5e6e7", text: "#8a4148" },
  },
  typography: {
    fontFamily:
      '"Segoe UI Variable", "Segoe UI", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif',
    fontSizeBody: 14,
    fontSizeSmall: 12,
    fontSizeCaption: 11,
    fontSizePageTitle: 25,
    fontSizeSectionTitle: 16,
    fontSizeBrand: 18,
  },
  radius: {
    small: 6,
    control: 8,
    large: 10,
    panel: 12,
  },
  controlHeight: 36,
  shadows: {
    panel: "0 1px 3px rgba(30, 41, 38, 0.04)",
    popup: "0 12px 32px rgba(30, 41, 38, 0.10)",
  },
} as const;

export const themeCssVariables = {
  "--app-bg": designTokens.colors.appBackground,
  "--surface": designTokens.colors.surface,
  "--surface-subtle": designTokens.colors.surfaceSubtle,
  "--surface-muted": designTokens.colors.surfaceMuted,
  "--surface-header": designTokens.colors.surfaceHeader,
  "--sidebar": designTokens.colors.sidebar,
  "--text": designTokens.colors.text,
  "--text-secondary": designTokens.colors.textSecondary,
  "--text-muted": designTokens.colors.textMuted,
  "--border": designTokens.colors.border,
  "--border-strong": designTokens.colors.borderStrong,
  "--accent": designTokens.colors.brand,
  "--accent-hover": designTokens.colors.brandHover,
  "--accent-soft": designTokens.colors.brandSoft,
  "--accent-soft-strong": designTokens.colors.brandSoftStrong,
  "--focus-ring": designTokens.colors.focusRing,
  "--action": designTokens.colors.action,
  "--action-hover": designTokens.colors.actionHover,
  "--row-feature": designTokens.colors.rowFeature,
  "--row-hover": designTokens.colors.rowHover,
  "--status-neutral-bg": designTokens.status.neutral.background,
  "--status-neutral-text": designTokens.status.neutral.text,
  "--status-design-bg": designTokens.status.design.background,
  "--status-design-text": designTokens.status.design.text,
  "--status-info-bg": designTokens.status.info.background,
  "--status-info-text": designTokens.status.info.text,
  "--status-warning-bg": designTokens.status.warning.background,
  "--status-warning-text": designTokens.status.warning.text,
  "--status-success-bg": designTokens.status.success.background,
  "--status-success-text": designTokens.status.success.text,
  "--status-completed-bg": designTokens.status.completed.background,
  "--status-completed-text": designTokens.status.completed.text,
  "--status-error-bg": designTokens.status.error.background,
  "--status-error-text": designTokens.status.error.text,
  "--font-family-base": designTokens.typography.fontFamily,
  "--font-size-body": `${designTokens.typography.fontSizeBody}px`,
  "--font-size-small": `${designTokens.typography.fontSizeSmall}px`,
  "--font-size-caption": `${designTokens.typography.fontSizeCaption}px`,
  "--font-size-page-title": `${designTokens.typography.fontSizePageTitle}px`,
  "--font-size-section-title": `${designTokens.typography.fontSizeSectionTitle}px`,
  "--font-size-brand": `${designTokens.typography.fontSizeBrand}px`,
  "--radius-small": `${designTokens.radius.small}px`,
  "--radius-control": `${designTokens.radius.control}px`,
  "--radius-large": `${designTokens.radius.large}px`,
  "--radius-panel": `${designTokens.radius.panel}px`,
  "--shadow-panel": designTokens.shadows.panel,
  "--shadow-popup": designTokens.shadows.popup,
} as CSSProperties;
